services:
  mysql-source:
    image: mysql:8.0
    container_name: mysql-source
    environment:
      MYSQL_ROOT_PASSWORD: Sandy@123
      MYSQL_DATABASE: source_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_source_data:/var/lib/mysql

  mysql-target:
    image: mysql:8.0
    container_name: mysql-target
    environment:
      MYSQL_ROOT_PASSWORD: Sandy@123
      MYSQL_DATABASE: target_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_target_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./spark_jobs:/app/spark_jobs
    depends_on:
      - mysql-source
      - mysql-target
      - spark-master
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  spark-master:
    build:
      context: ./spark_jobs
      dockerfile: ../Dockerfile.spark
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark_jobs:/opt/spark-apps

  spark-worker:
    build:
      context: ./spark_jobs
      dockerfile: ../Dockerfile.spark
    container_name: spark-worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_MODE=worker
    depends_on:
      - spark-master
    volumes:
      - ./spark_jobs:/opt/spark-apps

volumes:
  mysql_source_data:
  mysql_target_data:
